name: Trivy Secret Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        trivy --version
      
    - name: Run Trivy Secret Scan
      run: |
        secrets=$(trivy fs --scanners secret .)
        if [[ -n "$secrets" ]]; then
          echo "Secrets found:"
          echo "$secrets"
          exit 1
        fi
      
    - name: Success message
      if: success()
      run: echo "No secrets found in the repository!"
          trivy fs --scanners secret --exit-code 1 --severity CRITICAL ./
