name: Trivy Secret Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов для сканирования секретов

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          trivy-version: 'latest'

      - name: Scan for secrets
        id: trivy-scan
        run: |
          trivy fs --scanners secret --exit-code 1 --severity CRITICAL ./
